// matmul_krnl.sv -- top-level Vitis RTL kernel wrapper
//
// Instantiates, per the block diagram in CONTROL_INTERFACE.md:
//   axi_ctrl_wrapper (AXI4-Lite control regs) -> systolic_array (datapath)
//   -> axi_datamover_0 (PG022, generated by build/gen_ip.tcl) -> AXI4 masters
//
// The DataMover's MM2S (read) and S2MM (write) sides are two independent
// AXI4 master interfaces, not one shared bus (c_single_interface does not
// merge them - confirmed by inspecting the generated .veo), so this kernel
// exposes two memory ports: m_axi_gmem (read-only, for a_block/b_block) and
// m_axi_gmem1 (write-only, for c_block). kernel.xml binds arguments to
// whichever port actually carries them; see CONTROL_INTERFACE.md.
//
// ap_rst_n is active-low, matching the DataMover's *_aresetn ports directly;
// axi_ctrl_wrapper/systolic_array use the repo's active-high 'rst'
// convention, so it is inverted once here at the kernel boundary.

module matmul_krnl #(
    parameter LARGE_BUFFER_DIM = 256,
    parameter ARRAY_DIM        = 8,
    parameter MUL_WIDTH        = 16,
    parameter EXP_WIDTH        = 5,
    parameter ACC_WIDTH        = 48,
    parameter ACC_LSB          = -24
) (
    input  logic ap_clk,
    input  logic ap_rst_n,

    // s_axi_control (AXI4-Lite slave)
    input  logic [11:0] s_axi_control_awaddr,
    input  logic        s_axi_control_awvalid,
    output logic        s_axi_control_awready,
    input  logic [31:0] s_axi_control_wdata,
    input  logic [3:0]  s_axi_control_wstrb,
    input  logic        s_axi_control_wvalid,
    output logic        s_axi_control_wready,
    output logic [1:0]  s_axi_control_bresp,
    output logic        s_axi_control_bvalid,
    input  logic        s_axi_control_bready,
    input  logic [11:0] s_axi_control_araddr,
    input  logic        s_axi_control_arvalid,
    output logic        s_axi_control_arready,
    output logic [31:0] s_axi_control_rdata,
    output logic [1:0]  s_axi_control_rresp,
    output logic        s_axi_control_rvalid,
    input  logic        s_axi_control_rready,

    // m_axi_gmem: DataMover MM2S side (read-only master; a_block/b_block)
    output logic [3:0]  m_axi_gmem_arid,
    output logic [63:0] m_axi_gmem_araddr,
    output logic [7:0]  m_axi_gmem_arlen,
    output logic [2:0]  m_axi_gmem_arsize,
    output logic [1:0]  m_axi_gmem_arburst,
    output logic [2:0]  m_axi_gmem_arprot,
    output logic [3:0]  m_axi_gmem_arcache,
    output logic [3:0]  m_axi_gmem_aruser,
    output logic        m_axi_gmem_arvalid,
    input  logic        m_axi_gmem_arready,
    input  logic [63:0] m_axi_gmem_rdata,
    input  logic [1:0]  m_axi_gmem_rresp,
    input  logic        m_axi_gmem_rlast,
    input  logic        m_axi_gmem_rvalid,
    output logic        m_axi_gmem_rready,

    // m_axi_gmem1: DataMover S2MM side (write-only master; c_block)
    output logic [3:0]  m_axi_gmem1_awid,
    output logic [63:0] m_axi_gmem1_awaddr,
    output logic [7:0]  m_axi_gmem1_awlen,
    output logic [2:0]  m_axi_gmem1_awsize,
    output logic [1:0]  m_axi_gmem1_awburst,
    output logic [2:0]  m_axi_gmem1_awprot,
    output logic [3:0]  m_axi_gmem1_awcache,
    output logic [3:0]  m_axi_gmem1_awuser,
    output logic        m_axi_gmem1_awvalid,
    input  logic        m_axi_gmem1_awready,
    output logic [63:0] m_axi_gmem1_wdata,
    output logic [7:0]  m_axi_gmem1_wstrb,
    output logic        m_axi_gmem1_wlast,
    output logic        m_axi_gmem1_wvalid,
    input  logic        m_axi_gmem1_wready,
    input  logic [1:0]  m_axi_gmem1_bresp,
    input  logic        m_axi_gmem1_bvalid,
    output logic        m_axi_gmem1_bready
);

    localparam ADDR_WIDTH = 64;
    localparam BLK_WIDTH  = $clog2(LARGE_BUFFER_DIM) + 1;
    localparam CMD_WIDTH  = 104;

    logic rst;
    assign rst = ~ap_rst_n;

    // axi_ctrl_wrapper <-> systolic_array
    logic [ADDR_WIDTH-1:0] a_block_addr, b_block_addr, c_block_addr;
    logic [BLK_WIDTH-1:0]  blk_m, blk_k, blk_n;
    logic [1:0]            load_block_en;
    logic                  start_blk_comp, done_blk_comp, error_blk_comp;

    // systolic_array <-> axi_datamover_0
    logic [CMD_WIDTH-1:0] mm2s_cmd_tdata;
    logic                 mm2s_cmd_tvalid, mm2s_cmd_tready;
    logic [MUL_WIDTH-1:0] mm2s_tdata;
    logic                 mm2s_tvalid, mm2s_tready;
    logic [7:0]           mm2s_sts_tdata;
    logic                 mm2s_sts_tvalid, mm2s_sts_tready;

    logic [CMD_WIDTH-1:0]   s2mm_cmd_tdata;
    logic                   s2mm_cmd_tvalid, s2mm_cmd_tready;
    logic [MUL_WIDTH-1:0]   s2mm_tdata;
    logic [MUL_WIDTH/8-1:0] s2mm_tkeep;
    logic                   s2mm_tvalid, s2mm_tready, s2mm_tlast;
    logic [7:0]             s2mm_sts_tdata;
    logic                   s2mm_sts_tvalid, s2mm_sts_tready;

    ////////////////////////////////////////////////////////////////////////////////
    // AXI4-LITE CONTROL
    ////////////////////////////////////////////////////////////////////////////////

    axi_ctrl_wrapper #(.LARGE_BUFFER_DIM(LARGE_BUFFER_DIM),
                       .ADDR_WIDTH(ADDR_WIDTH)) ctrl_0(
        .clk(ap_clk),
        .rst(rst),
        .s_axi_awaddr(s_axi_control_awaddr),
        .s_axi_awvalid(s_axi_control_awvalid),
        .s_axi_awready(s_axi_control_awready),
        .s_axi_wdata(s_axi_control_wdata),
        .s_axi_wstrb(s_axi_control_wstrb),
        .s_axi_wvalid(s_axi_control_wvalid),
        .s_axi_wready(s_axi_control_wready),
        .s_axi_bresp(s_axi_control_bresp),
        .s_axi_bvalid(s_axi_control_bvalid),
        .s_axi_bready(s_axi_control_bready),
        .s_axi_araddr(s_axi_control_araddr),
        .s_axi_arvalid(s_axi_control_arvalid),
        .s_axi_arready(s_axi_control_arready),
        .s_axi_rdata(s_axi_control_rdata),
        .s_axi_rresp(s_axi_control_rresp),
        .s_axi_rvalid(s_axi_control_rvalid),
        .s_axi_rready(s_axi_control_rready),
        .a_block_addr,
        .b_block_addr,
        .c_block_addr,
        .blk_m,
        .blk_k,
        .blk_n,
        .load_block_en,
        .start_blk_comp,
        .done_blk_comp,
        .error_blk_comp
    );

    ////////////////////////////////////////////////////////////////////////////////
    // DATAPATH
    ////////////////////////////////////////////////////////////////////////////////

    systolic_array #(.LARGE_BUFFER_DIM(LARGE_BUFFER_DIM),
                     .ARRAY_DIM(ARRAY_DIM),
                     .MUL_WIDTH(MUL_WIDTH),
                     .EXP_WIDTH(EXP_WIDTH),
                     .ACC_WIDTH(ACC_WIDTH),
                     .ACC_LSB(ACC_LSB)) systolic_array_0(
        .clk(ap_clk),
        .rst,
        .a_block_addr,
        .b_block_addr,
        .c_block_addr,
        .blk_m,
        .blk_k,
        .blk_n,
        .load_block_en,
        .start_blk_comp,
        .done_blk_comp,
        .error_blk_comp,
        .mm2s_cmd_tdata,
        .mm2s_cmd_tvalid,
        .mm2s_cmd_tready,
        .mm2s_tdata,
        .mm2s_tvalid,
        .mm2s_tready,
        .mm2s_sts_tdata,
        .mm2s_sts_tvalid,
        .mm2s_sts_tready,
        .s2mm_cmd_tdata,
        .s2mm_cmd_tvalid,
        .s2mm_cmd_tready,
        .s2mm_tdata,
        .s2mm_tkeep,
        .s2mm_tvalid,
        .s2mm_tready,
        .s2mm_tlast,
        .s2mm_sts_tdata,
        .s2mm_sts_tvalid,
        .s2mm_sts_tready
    );

    ////////////////////////////////////////////////////////////////////////////////
    // AXI DATAMOVER (generated by build/gen_ip.tcl; see that script for CONFIG.*)
    ////////////////////////////////////////////////////////////////////////////////

    axi_datamover_0 datamover_0(
        .m_axi_mm2s_aclk(ap_clk),
        .m_axi_mm2s_aresetn(ap_rst_n),
        .mm2s_err(),
        .m_axis_mm2s_cmdsts_aclk(ap_clk),
        .m_axis_mm2s_cmdsts_aresetn(ap_rst_n),
        .s_axis_mm2s_cmd_tvalid(mm2s_cmd_tvalid),
        .s_axis_mm2s_cmd_tready(mm2s_cmd_tready),
        .s_axis_mm2s_cmd_tdata(mm2s_cmd_tdata),
        .m_axis_mm2s_sts_tvalid(mm2s_sts_tvalid),
        .m_axis_mm2s_sts_tready(mm2s_sts_tready),
        .m_axis_mm2s_sts_tdata(mm2s_sts_tdata),
        .m_axis_mm2s_sts_tkeep(),
        .m_axis_mm2s_sts_tlast(),
        .m_axi_mm2s_arid(m_axi_gmem_arid),
        .m_axi_mm2s_araddr(m_axi_gmem_araddr),
        .m_axi_mm2s_arlen(m_axi_gmem_arlen),
        .m_axi_mm2s_arsize(m_axi_gmem_arsize),
        .m_axi_mm2s_arburst(m_axi_gmem_arburst),
        .m_axi_mm2s_arprot(m_axi_gmem_arprot),
        .m_axi_mm2s_arcache(m_axi_gmem_arcache),
        .m_axi_mm2s_aruser(m_axi_gmem_aruser),
        .m_axi_mm2s_arvalid(m_axi_gmem_arvalid),
        .m_axi_mm2s_arready(m_axi_gmem_arready),
        .m_axi_mm2s_rdata(m_axi_gmem_rdata),
        .m_axi_mm2s_rresp(m_axi_gmem_rresp),
        .m_axi_mm2s_rlast(m_axi_gmem_rlast),
        .m_axi_mm2s_rvalid(m_axi_gmem_rvalid),
        .m_axi_mm2s_rready(m_axi_gmem_rready),
        .m_axis_mm2s_tdata(mm2s_tdata),
        .m_axis_mm2s_tkeep(),
        .m_axis_mm2s_tlast(),
        .m_axis_mm2s_tvalid(mm2s_tvalid),
        .m_axis_mm2s_tready(mm2s_tready),

        .m_axi_s2mm_aclk(ap_clk),
        .m_axi_s2mm_aresetn(ap_rst_n),
        .s2mm_err(),
        .m_axis_s2mm_cmdsts_awclk(ap_clk),
        .m_axis_s2mm_cmdsts_aresetn(ap_rst_n),
        .s_axis_s2mm_cmd_tvalid(s2mm_cmd_tvalid),
        .s_axis_s2mm_cmd_tready(s2mm_cmd_tready),
        .s_axis_s2mm_cmd_tdata(s2mm_cmd_tdata),
        .m_axis_s2mm_sts_tvalid(s2mm_sts_tvalid),
        .m_axis_s2mm_sts_tready(s2mm_sts_tready),
        .m_axis_s2mm_sts_tdata(s2mm_sts_tdata),
        .m_axis_s2mm_sts_tkeep(),
        .m_axis_s2mm_sts_tlast(),
        .m_axi_s2mm_awid(m_axi_gmem1_awid),
        .m_axi_s2mm_awaddr(m_axi_gmem1_awaddr),
        .m_axi_s2mm_awlen(m_axi_gmem1_awlen),
        .m_axi_s2mm_awsize(m_axi_gmem1_awsize),
        .m_axi_s2mm_awburst(m_axi_gmem1_awburst),
        .m_axi_s2mm_awprot(m_axi_gmem1_awprot),
        .m_axi_s2mm_awcache(m_axi_gmem1_awcache),
        .m_axi_s2mm_awuser(m_axi_gmem1_awuser),
        .m_axi_s2mm_awvalid(m_axi_gmem1_awvalid),
        .m_axi_s2mm_awready(m_axi_gmem1_awready),
        .m_axi_s2mm_wdata(m_axi_gmem1_wdata),
        .m_axi_s2mm_wstrb(m_axi_gmem1_wstrb),
        .m_axi_s2mm_wlast(m_axi_gmem1_wlast),
        .m_axi_s2mm_wvalid(m_axi_gmem1_wvalid),
        .m_axi_s2mm_wready(m_axi_gmem1_wready),
        .m_axi_s2mm_bresp(m_axi_gmem1_bresp),
        .m_axi_s2mm_bvalid(m_axi_gmem1_bvalid),
        .m_axi_s2mm_bready(m_axi_gmem1_bready),
        .s_axis_s2mm_tdata(s2mm_tdata),
        .s_axis_s2mm_tkeep(s2mm_tkeep),
        .s_axis_s2mm_tlast(s2mm_tlast),
        .s_axis_s2mm_tvalid(s2mm_tvalid),
        .s_axis_s2mm_tready(s2mm_tready)
    );

endmodule
